#!/bin/bash
# Install Zotero dependencies on Ubuntu/Debian

echo "=================================================="
echo "Installing Zotero Dependencies"
echo "=================================================="
echo ""
echo "Please run this command to install required dependencies:"
echo ""
echo "sudo apt-get update && sudo apt-get install -y \\"
echo "    libdbus-glib-1-2 \\"
echo "    libgtk-3-0 \\"
echo "    libnss3 \\"
echo "    libx11-xcb1 \\"
echo "    libxcomposite1 \\"
echo "    libxdamage1 \\"
echo "    libxrandr2 \\"
echo "    libxtst6 \\"
echo "    libasound2 \\"
echo "    libatspi2.0-0 \\"
echo "    libdrm2 \\"
echo "    libgbm1 \\"
echo "    libxss1"
echo ""
echo "After installing dependencies, Zotero should work!"
echo ""
echo "Alternative: Use Windows Zotero with WSL"
echo "==========================================="
echo "Since you're on WSL, you might prefer using the Windows version"
echo "of Zotero which is already installed and working."
echo ""
echo "The Linux version in WSL will work but may have display issues."
echo "The Windows version integrates better with your system."