#!/usr/bin/env python3
"""Scitex color module — delegates to figrecipe.colors (single source of truth).

Kept for backward compatibility: ``from scitex.plt.color import PARAMS`` still works.
"""

# Core exports from figrecipe.colors
from figrecipe.colors import (
    DEF_ALPHA,
    HEX,
    PARAMS,
    RGB,
    RGB_NORM,
    RGBA,
    RGBA_NORM,
    bgr2bgra,
    bgr2rgb,
    bgra2bgr,
    bgra2hex,
    bgra2rgba,
    cycle_color,
    cycle_color_bgr,
    cycle_color_rgb,
    gen_interpolate,
    get_categorical_colors_from_conf_matap,
    get_color_from_conf_matap,
    get_colors_from_conf_matap,
    gradiate_color,
    gradiate_color_bgr,
    gradiate_color_bgra,
    gradiate_color_rgb,
    gradiate_color_rgba,
    interpolate,
    rgb2bgr,
    rgb2rgba,
    rgba2bgra,
    rgba2hex,
    rgba2rgb,
    str2bgr,
    str2bgra,
    str2hex,
    str2rgb,
    str2rgba,
    to_hex,
    to_rgb,
    to_rgba,
    update_alpha,
)

# scitex-specific extras (not in figrecipe)
from ._add_hue_col import add_hue_col
from ._vizualize_colors import vizualize_colors

__all__ = [
    "PARAMS",
    "DEF_ALPHA",
    "RGB",
    "RGB_NORM",
    "RGBA",
    "RGBA_NORM",
    "HEX",
    "add_hue_col",
    "bgr2bgra",
    "bgr2rgb",
    "bgra2bgr",
    "bgra2hex",
    "bgra2rgba",
    "cycle_color",
    "cycle_color_bgr",
    "cycle_color_rgb",
    "gen_interpolate",
    "get_categorical_colors_from_conf_matap",
    "get_color_from_conf_matap",
    "get_colors_from_conf_matap",
    "gradiate_color",
    "gradiate_color_bgr",
    "gradiate_color_bgra",
    "gradiate_color_rgb",
    "gradiate_color_rgba",
    "interpolate",
    "rgb2bgr",
    "rgb2rgba",
    "rgba2bgra",
    "rgba2hex",
    "rgba2rgb",
    "str2bgr",
    "str2bgra",
    "str2hex",
    "str2rgb",
    "str2rgba",
    "to_hex",
    "to_rgb",
    "to_rgba",
    "update_alpha",
    "vizualize_colors",
]

# EOF
