#!/bin/bash
# PAC Collection Download Commands
# Generated by MCP Analysis

# SETUP_COMMANDS
# Setup authentication and directories
mkdir -p ~/.scitex/scholar/library/pac
cd ~/.scitex/scholar/library/pac

# Verify authentication cookies exist
ls -la ~/.scitex/scholar/cache/chrome/auth/


# PRIORITY_1_DOWNLOADS
# Priority 1: Open Access Papers (No Auth Required)
# These can be downloaded directly

# arXiv papers
python -m scitex.scholar.download --source arxiv --project pac

# PubMed/PMC papers
python -m scitex.scholar.download --source pubmed --project pac

# Semantic Scholar papers
python -m scitex.scholar.download --source semantic_scholar --project pac --batch-size 10


# PRIORITY_2_DOWNLOADS
# Priority 2: Authenticated Downloads
# Requires university authentication

# ScienceDirect papers (Elsevier)
python -m scitex.scholar.download --source sciencedirect --project pac --auth openathens

# IEEE papers
python -m scitex.scholar.download --source ieee --project pac --auth openathens

# DOI resolution with authentication
python -m scitex.scholar.download --source doi_resolver --project pac --auth openathens


# MONITORING_COMMANDS
# Progress monitoring
python -m scitex.scholar.status --project pac

# Resume failed downloads
python -m scitex.scholar.download --project pac --resume

# Generate final report
python -m scitex.scholar.report --project pac --format detailed


