#!/usr/bin/env python3
# Timestamp: "2025-12-28 (ywatanabe)"
# File: ./mcp_servers/scitex-analyzer/helpers/documentation.py

"""Documentation generation helpers."""

from pathlib import Path
from typing import Dict, Optional


async def generate_readme_from_analysis(analysis: Dict, project: Path) -> str:
    """Generate README from project analysis.

    Parameters
    ----------
    analysis : dict
        Project analysis results
    project : Path
        Path to the project directory

    Returns
    -------
    str
        README content
    """
    return f"""# {project.name}

## Project Analysis Summary

- **Files analyzed**: {analysis.get("project_structure", {}).get("total_files", 0)}
- **SciTeX compliance**: {analysis.get("code_patterns", {}).get("compliance_score", 0)}%
- **Configuration score**: {analysis.get("configurations", {}).get("consistency_score", 0)}%

## Recommendations

{chr(10).join(f"- {rec.get('suggestion', '')}" for rec in analysis.get("recommendations", [])[:5])}

## Generated by SciTeX Analyzer
"""


async def generate_api_docs(project: Path) -> str:
    """Generate API documentation.

    Parameters
    ----------
    project : Path
        Path to the project directory

    Returns
    -------
    str
        API documentation content
    """
    return """# API Documentation

## Functions

Documentation for project functions will be generated here.

## Classes

Documentation for project classes will be generated here.

## Configuration

See CONFIGURATION.md for configuration details.
"""


async def generate_user_guide(project: Path, analysis: Dict) -> str:
    """Generate user guide.

    Parameters
    ----------
    project : Path
        Path to the project directory
    analysis : dict
        Project analysis results

    Returns
    -------
    str
        User guide content
    """
    return f"""# User Guide

## Getting Started

This project uses the SciTeX framework for scientific computing.

## Project Structure

{chr(10).join(f"- `{d}/`" for d in analysis.get("project_structure", {}).get("existing_directories", []))}

## Usage

1. Install requirements: `pip install -r requirements.txt`
2. Run main script: `python scripts/main.py`
3. Check results in `results/` directory

## Configuration

Edit files in `config/` directory to customize analysis parameters.
"""


async def generate_config_docs(project: Path) -> Optional[str]:
    """Generate configuration documentation.

    Parameters
    ----------
    project : Path
        Path to the project directory

    Returns
    -------
    str or None
        Configuration documentation content, or None if no config dir
    """
    config_dir = project / "config"
    if not config_dir.exists():
        return None

    return """# Configuration Documentation

## Configuration Files

### PATH.yaml
File path configuration for the project.

### PARAMS.yaml
Analysis parameters and settings.

### COLORS.yaml
Color scheme for visualizations.

## Usage

```python
CONFIG = stx.io.load_configs()
threshold = CONFIG.PARAMS.ANALYSIS_THRESHOLD
data_path = CONFIG.PATH.DATA
```
"""


# EOF
